source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SCTableViewCell_Example', :exclusive => true do
  pod "SCTableViewCell", :path => "../"
end

target 'SCTableViewCell_Tests', :exclusive => true do
  pod "SCTableViewCell", :path => "../"

  
end
